/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HostelRouteImport } from './routes/hostel'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherNoticesRouteImport } from './routes/teacher.notices'
import { Route as TeacherMaterialsRouteImport } from './routes/teacher.materials'
import { Route as TeacherLessonPlansRouteImport } from './routes/teacher.lesson-plans'
import { Route as TeacherLeaveRouteImport } from './routes/teacher.leave'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherClassesRouteImport } from './routes/teacher.classes'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as SuperUsersRouteImport } from './routes/super.users'
import { Route as SuperBillingRouteImport } from './routes/super.billing'
import { Route as SubjectsIdRouteImport } from './routes/subjects.$id'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentNoticesRouteImport } from './routes/student.notices'
import { Route as StudentMaterialsRouteImport } from './routes/student.materials'
import { Route as StudentLibraryRouteImport } from './routes/student.library'
import { Route as StudentFeesRouteImport } from './routes/student.fees'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as ParentDashboardRouteImport } from './routes/parent.dashboard'
import { Route as ParentChildrenRouteImport } from './routes/parent.children'
import { Route as ExamsIdRouteImport } from './routes/exams.$id'
import { Route as ClassesIdRouteImport } from './routes/classes.$id'
import { Route as AssignmentsIdRouteImport } from './routes/assignments.$id'
import { Route as AdminInfrastructureRouteImport } from './routes/admin.infrastructure'
import { Route as AdminExpensesRouteImport } from './routes/admin.expenses'
import { Route as AdminDmsRouteImport } from './routes/admin.dms'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAssetsRouteImport } from './routes/admin.assets'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as SuperInstitutesIndexRouteImport } from './routes/super.institutes.index'
import { Route as TeacherMaterialsIdRouteImport } from './routes/teacher.materials.$id'
import { Route as TeacherLessonPlansIdRouteImport } from './routes/teacher.lesson-plans.$id'
import { Route as SuperInstitutesNewRouteImport } from './routes/super.institutes.new'
import { Route as SuperInstitutesIdRouteImport } from './routes/super.institutes.$id'
import { Route as ParentChildrenIdRouteImport } from './routes/parent.children.$id'
import { Route as AdminAdmissionsIdRouteImport } from './routes/admin.admissions.$id'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
})
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
})
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
})
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
})
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
})
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
})
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
})
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
})
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
})
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
})
const HostelRoute = HostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => rootRouteImport,
})
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
})
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
})
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
})
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
})
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
})
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
})
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
})
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
})
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
})
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const TeacherNoticesRoute = TeacherNoticesRouteImport.update({
  id: '/teacher/notices',
  path: '/teacher/notices',
  getParentRoute: () => rootRouteImport,
})
const TeacherMaterialsRoute = TeacherMaterialsRouteImport.update({
  id: '/teacher/materials',
  path: '/teacher/materials',
  getParentRoute: () => rootRouteImport,
})
const TeacherLessonPlansRoute = TeacherLessonPlansRouteImport.update({
  id: '/teacher/lesson-plans',
  path: '/teacher/lesson-plans',
  getParentRoute: () => rootRouteImport,
})
const TeacherLeaveRoute = TeacherLeaveRouteImport.update({
  id: '/teacher/leave',
  path: '/teacher/leave',
  getParentRoute: () => rootRouteImport,
})
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => rootRouteImport,
})
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/teacher/classes',
  path: '/teacher/classes',
  getParentRoute: () => rootRouteImport,
})
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/teacher/attendance',
  path: '/teacher/attendance',
  getParentRoute: () => rootRouteImport,
})
const SuperUsersRoute = SuperUsersRouteImport.update({
  id: '/super/users',
  path: '/super/users',
  getParentRoute: () => rootRouteImport,
})
const SuperBillingRoute = SuperBillingRouteImport.update({
  id: '/super/billing',
  path: '/super/billing',
  getParentRoute: () => rootRouteImport,
})
const SubjectsIdRoute = SubjectsIdRouteImport.update({
  id: '/subjects/$id',
  path: '/subjects/$id',
  getParentRoute: () => rootRouteImport,
})
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
})
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/student/timetable',
  path: '/student/timetable',
  getParentRoute: () => rootRouteImport,
})
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/student/results',
  path: '/student/results',
  getParentRoute: () => rootRouteImport,
})
const StudentNoticesRoute = StudentNoticesRouteImport.update({
  id: '/student/notices',
  path: '/student/notices',
  getParentRoute: () => rootRouteImport,
})
const StudentMaterialsRoute = StudentMaterialsRouteImport.update({
  id: '/student/materials',
  path: '/student/materials',
  getParentRoute: () => rootRouteImport,
})
const StudentLibraryRoute = StudentLibraryRouteImport.update({
  id: '/student/library',
  path: '/student/library',
  getParentRoute: () => rootRouteImport,
})
const StudentFeesRoute = StudentFeesRouteImport.update({
  id: '/student/fees',
  path: '/student/fees',
  getParentRoute: () => rootRouteImport,
})
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
})
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/student/attendance',
  path: '/student/attendance',
  getParentRoute: () => rootRouteImport,
})
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/student/assignments',
  path: '/student/assignments',
  getParentRoute: () => rootRouteImport,
})
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/parent/dashboard',
  path: '/parent/dashboard',
  getParentRoute: () => rootRouteImport,
})
const ParentChildrenRoute = ParentChildrenRouteImport.update({
  id: '/parent/children',
  path: '/parent/children',
  getParentRoute: () => rootRouteImport,
})
const ExamsIdRoute = ExamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExamsRoute,
})
const ClassesIdRoute = ClassesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClassesRoute,
})
const AssignmentsIdRoute = AssignmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssignmentsRoute,
})
const AdminInfrastructureRoute = AdminInfrastructureRouteImport.update({
  id: '/admin/infrastructure',
  path: '/admin/infrastructure',
  getParentRoute: () => rootRouteImport,
})
const AdminExpensesRoute = AdminExpensesRouteImport.update({
  id: '/admin/expenses',
  path: '/admin/expenses',
  getParentRoute: () => rootRouteImport,
})
const AdminDmsRoute = AdminDmsRouteImport.update({
  id: '/admin/dms',
  path: '/admin/dms',
  getParentRoute: () => rootRouteImport,
})
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
})
const AdminAssetsRoute = AdminAssetsRouteImport.update({
  id: '/admin/assets',
  path: '/admin/assets',
  getParentRoute: () => rootRouteImport,
})
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admin/admissions',
  path: '/admin/admissions',
  getParentRoute: () => rootRouteImport,
})
const SuperInstitutesIndexRoute = SuperInstitutesIndexRouteImport.update({
  id: '/super/institutes/',
  path: '/super/institutes/',
  getParentRoute: () => rootRouteImport,
})
const TeacherMaterialsIdRoute = TeacherMaterialsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeacherMaterialsRoute,
})
const TeacherLessonPlansIdRoute = TeacherLessonPlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeacherLessonPlansRoute,
})
const SuperInstitutesNewRoute = SuperInstitutesNewRouteImport.update({
  id: '/super/institutes/new',
  path: '/super/institutes/new',
  getParentRoute: () => rootRouteImport,
})
const SuperInstitutesIdRoute = SuperInstitutesIdRouteImport.update({
  id: '/super/institutes/$id',
  path: '/super/institutes/$id',
  getParentRoute: () => rootRouteImport,
})
const ParentChildrenIdRoute = ParentChildrenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ParentChildrenRoute,
})
const AdminAdmissionsIdRoute = AdminAdmissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdmissionsRoute,
})

const AssignmentsRouteChildren = {
  AssignmentsIdRoute: AssignmentsIdRoute,
}

const AssignmentsRouteWithChildren = AssignmentsRoute._addFileChildren(
  AssignmentsRouteChildren,
)

const ClassesRouteChildren = {
  ClassesIdRoute: ClassesIdRoute,
}

const ClassesRouteWithChildren =
  ClassesRoute._addFileChildren(ClassesRouteChildren)

const ExamsRouteChildren = {
  ExamsIdRoute: ExamsIdRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

const StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const AdminAdmissionsRouteChildren = {
  AdminAdmissionsIdRoute: AdminAdmissionsIdRoute,
}

const AdminAdmissionsRouteWithChildren = AdminAdmissionsRoute._addFileChildren(
  AdminAdmissionsRouteChildren,
)

const ParentChildrenRouteChildren = {
  ParentChildrenIdRoute: ParentChildrenIdRoute,
}

const ParentChildrenRouteWithChildren = ParentChildrenRoute._addFileChildren(
  ParentChildrenRouteChildren,
)

const TeacherLessonPlansRouteChildren = {
  TeacherLessonPlansIdRoute: TeacherLessonPlansIdRoute,
}

const TeacherLessonPlansRouteWithChildren =
  TeacherLessonPlansRoute._addFileChildren(TeacherLessonPlansRouteChildren)

const TeacherMaterialsRouteChildren = {
  TeacherMaterialsIdRoute: TeacherMaterialsIdRoute,
}

const TeacherMaterialsRouteWithChildren =
  TeacherMaterialsRoute._addFileChildren(TeacherMaterialsRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssignmentsRoute: AssignmentsRouteWithChildren,
  AttendanceRoute: AttendanceRoute,
  ClassesRoute: ClassesRouteWithChildren,
  CommunicationRoute: CommunicationRoute,
  EmployeesRoute: EmployeesRoute,
  ExamsRoute: ExamsRouteWithChildren,
  FeesRoute: FeesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HostelRoute: HostelRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ParentsRoute: ParentsRoute,
  PayrollRoute: PayrollRoute,
  ProfileRoute: ProfileRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StudentsRoute: StudentsRouteWithChildren,
  TimetableRoute: TimetableRoute,
  TransportRoute: TransportRoute,
  AdminAdmissionsRoute: AdminAdmissionsRouteWithChildren,
  AdminAssetsRoute: AdminAssetsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDmsRoute: AdminDmsRoute,
  AdminExpensesRoute: AdminExpensesRoute,
  AdminInfrastructureRoute: AdminInfrastructureRoute,
  ParentChildrenRoute: ParentChildrenRouteWithChildren,
  ParentDashboardRoute: ParentDashboardRoute,
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentFeesRoute: StudentFeesRoute,
  StudentLibraryRoute: StudentLibraryRoute,
  StudentMaterialsRoute: StudentMaterialsRoute,
  StudentNoticesRoute: StudentNoticesRoute,
  StudentResultsRoute: StudentResultsRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  SubjectsIdRoute: SubjectsIdRoute,
  SuperBillingRoute: SuperBillingRoute,
  SuperUsersRoute: SuperUsersRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherClassesRoute: TeacherClassesRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherLeaveRoute: TeacherLeaveRoute,
  TeacherLessonPlansRoute: TeacherLessonPlansRouteWithChildren,
  TeacherMaterialsRoute: TeacherMaterialsRouteWithChildren,
  TeacherNoticesRoute: TeacherNoticesRoute,
  SuperInstitutesIdRoute: SuperInstitutesIdRoute,
  SuperInstitutesNewRoute: SuperInstitutesNewRoute,
  SuperInstitutesIndexRoute: SuperInstitutesIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)

